### ISSUE TITLE
Window Extension question

### ISSUE THREAD

**Issue by echoless3484** [True-Fantom/true-fantom.github.io#3]
Saw your window extension and that it has fullscreen reporter, can you possibly make that an extension on its own, I've been trying but I'm 100% new to javascript, here's my code so far:

`(Scratch => {
  'use strict';

  class Window {
  
    getInfo() {
      return {
	  
        id: 'fullscreen',
        name: 'Fullscreen',
		
        blocks: [
          {
            opcode: 'fullscreen',
            blockType: Scratch.BlockType.REPORTER,
            text: 'fullscreen?'
          }
        ]
      };
    }
    fullscreen() {
      try {return document.fullscreenElement === null ? false : true} catch(err) {return ''}
    }
  }
  Scratch.extensions.register(new Fullscreen());
})(Scratch);`

(this is your code, just trying to edit it into one single extension)

**Comment by True-Fantom** [comment]
@echoless3484 Please excuse the wait...

Most of the extensions in my profile are just prototypes, which are either full of bugs or almost no new blocks at all. If I finish the extension, I will immediately post it on the official TW website. So Window is just an unstable version of Network3 for now, with a few new blocks.

However, if you need a block to define fullscreen mode, I would recommend this code to you:

```
(Scratch => {
  'use strict';

  class ScreenMode {

    getInfo() {
      return {

        id: 'screenmode',
        name: 'ScreenMode',

        blocks: [
          {
            opcode: 'screen_mode_block',
            blockType: Scratch.BlockType.REPORTER,
            text: 'screen mode'
          }
        ]
      };
    }

    screen_mode_block() {
      try {
        return document.fullscreenElement === null ? 'window' : 'full';
      }
      catch(err) {
        return '';
      }
    }
  }

  Scratch.extensions.register(new ScreenMode());
})(Scratch);
```

There was only one error in your code, the class name did not match at the beginning and at the very end:
`class Window {` and `Scratch.extensions.register(new Fullscreen());`

I fixed this and slightly modified the text in the extension.

By the way, it does not use a logical block, since the screen can have 3 states: undefined, full and normal.
So the block outputs "" or "full" or "window".

**Comment by True-Fantom** [comment]
@echoless3484 I wish you good luck in learning JS, it's really interesting :)
